version: "3.9"
services:
  rabbitmq:
    image: acme-rabbit-mq:test
    hostname: "rabbitmq.{{.Task.Slot}}.{{.Task.ID}}"
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq.{{.Task.Slot}}.{{.Task.ID}}
      - RABBITMQ_ERLANG_COOKIE=supersecretcookievalue
